### ISSUE TITLE
Support Github app oauth token rather that a personal token

### ISSUE THREAD

**Issue by simonweil** [kunalnagarco/action-cve#113]
Hi,

As the personal token depends on the user existing it would be really great to be able to use an app for the required access.

Thanks so much

**Comment by kunalnagar** [comment]
@simonweil - Thanks for the suggestion. I will take a look into this and update here!

**Comment by steven-xufan** [comment]
just wanted to add a comment that our team is using github application (instead of personal token) with the help of another action:
```
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.YOUR_APP_ID }}
          application_private_key: ${{ secrets.YOUR_APP_PRIVATE_KEY }}

      - uses: kunalnagarco/action-cve@v1.7.13
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          slack_webhook: ${{ secrets.YOUR_WEBHOOK }}
          count: 1
```
