### ISSUE TITLE
Add a filter by Advisory Severity

### ISSUE THREAD

**Issue by joris974** [kunalnagarco/action-cve#144]
Could there be an optional parameter to notify only on a given set of Advisory Severity?

```yml
with:
    github-token: ...
    severities: |
      HIGH
      CRITICAL
```

Something like this
```ts
export const filterAlertsByAdvisorySeverity = (
  alerts: Alert[],
  severities: AdvisorySeverity[],
) => {
  if (severities.length === 0) {
    return alerts;
  }
  return alerts.filter((alert) =>
    alert.advisory !== undefined
      ? severities.includes(alert.advisory.severity)
      : true
  );
};
```
