### ISSUE TITLE
Severity filter not working?

### ISSUE THREAD

**Issue by mauritz-lovgren** [kunalnagarco/action-cve#186]
Hi,

I am getting vulnerabilities with MEDIUM severity even though I have specified the following:

```
jobs:
  notify-vulnerabilites:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Notify Vulnerabilities
        uses: kunalnagarco/action-cve@v1.13.2
        with:
          token: ${{ secrets.WF_READ_PKG }}
          slack_webhook: ${{ inputs.slack-webhook }}
          severity: high,critical
```

Received in my target Slack channel:

```
Package name: org.apache.commons:commons-compress
Vulnerability Version Range: >= 1.3, < 1.26.0
Patched Version: 1.26.0
Severity: HIGH
Summary: Apache Commons Compress: Denial of service caused by an infinite loop for a corrupted DUMP file

Package name: org.apache.james:apache-mime4j-core
Vulnerability Version Range: < 0.8.10
Patched Version: 0.8.10
Severity: MEDIUM
Summary: Apache James MIME4J improper input validation vulnerability

Package name: org.apache.commons:commons-compress
Vulnerability Version Range: >= 1.21, < 1.26.0
Patched Version: 1.26.0
Severity: HIGH
Summary: Apache Commons Compress: OutOfMemoryError unpacking broken Pack200 file

Package name: org.apache.james:apache-mime4j-storage
Vulnerability Version Range: < 0.8.9
Patched Version: 0.8.9
Severity: MEDIUM
Summary: Apache James MIME4J vulnerable to information disclosure to local users

Package name: io.netty:netty-handler
Vulnerability Version Range: < 4.1.94.Final
Patched Version: 4.1.94.Final
Severity: MEDIUM
Summary: netty-handler SniHandler 16MB allocation
```

Is this to be expected, or have I specified the severity attribute wrong?
